CREATE TABLE noteful_notes (
    noteid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    folderid INTEGER NOT NULL,
    FOREIGN KEY (folderid) REFERENCES noteful_folders (folderid),
    date_published TIMESTAMP DEFAULT now() NOT NULL
);