CREATE TABLE noteful_notes (
    noteId INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    folderId INTEGER NOT NULL,
    FOREIGN KEY (folderId) REFERENCES noteful_folders (folderId),
    date_published TIMESTAMP DEFAULT now() NOT NULL
);